name: npm_publish

on:
  workflow_dispatch:
    inputs:
      NPM_PUBLISH_TAG:
        type: string
        required: true
      INCREMENT_PATCH:
        type: choice
        options:
          - false
          - true
        defaut: false

jobs:

  npm_publish:
    uses: newscorp-djcs/reusable-workflows/.github/workflows/npm_publish.yml@main
    with:
      NPM_PUBLISH_TAG: ${{ github.event.inputs.NPM_PUBLISH_TAG }}
      INCREMENT_PATCH: ${{ github.event.inputs.INCREMENT_PATCH }}
    secrets: inherit

